CREATE DATABASE PROPRIEDADE;
USE PROPRIEDADE;

CREATE TABLE TBL_USUARIOS(
     USU_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
     USU_NOME VARCHAR(20),
     USU_EMAIL VARCHAR(40));

CREATE TABLE TBL_TAREFA(
     TAR_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
     TAR_SETOR VARCHAR(20),
     TAR_PRIORIDADE VARCHAR(40),
     TAR_DESCRICAO VARCHAR(50),
     TAR_STATUS VARCHAR(60));
     
ALTER TABLE TBL_TAREFA
ADD COLUMN USU_CODIGO INT;

ALTER TABLE TBL_TAREFA  
ADD CONSTRAINT FK_USU_CODIGO
FOREIGN KEY (Usu_Codigo) REFERENCES Tbl_Usuarios(Usu_Codigo)

SELECT*FROM TBL_TAREFA; 